-- Facilities + roster metadata. Run after schema.sql.
begin;
insert into facility (name, tagline, location, sort_order, beds, rdo, rdcs, nha, don, survey, rating_overall, rating_staffing, total_staff, open_roles) values ('Champion City', 'Rehabilitation & Nursing Center', 'Pittsburgh, PA', 1, '187 beds', 'Shala Currey', 'Christina Delisio', 'Maribeth Tarpley', 'Cerise Roberts', '🟡 Active Monitoring', 1, 1, '49', '3');
insert into facility (name, tagline, location, sort_order, beds, rdo, rdcs, nha, don, survey, rating_overall, rating_staffing, total_staff, open_roles) values ('Eden', 'Center for Nursing and Healing', 'formerly Platinum Ridge', 2, '97 beds', 'Shala Currey', 'Christina Delisio', 'Hannah Neal', 'Monica McWilson', '🟡 Monitoring', 1, 2, '35.5', '1');
insert into facility (name, tagline, location, sort_order, beds, rdo, rdcs, nha, don, survey, rating_overall, rating_staffing, total_staff, open_roles) values ('Highland Park', 'Rehabilitation & Nursing Center', null, 3, '80 Beds', 'Shala Currey', 'Christina Delisio', 'Blake Apsokardu', 'Bernadine "Dina" Billings', '🟡 Annual Survey Overdue', 5, 2, '29', '0');
insert into facility (name, tagline, location, sort_order, beds, rdo, rdcs, nha, don, survey, rating_overall, rating_staffing, total_staff, open_roles) values ('The Pearl', 'Rehabilitation & Nursing Center', null, 4, '— (confirm)', 'Shala Currey', 'Christina Delisio', '[OPEN — NHA Vacant]', 'Tiffany Johnson', '🟡 Active Monitoring', 1, 1, '0', '2');
insert into facility (name, tagline, location, sort_order, beds, rdo, rdcs, nha, don, survey, rating_overall, rating_staffing, total_staff, open_roles) values ('Aristos', 'Rehabilitation & Nursing Center', null, 5, '56 beds', 'Stacie Atherton', 'Amanda Seibert', 'Yehuda Biren', '— OPEN —', '🔴 Active Citations — Verify CMP Status', 3, 1, '4', '2');
insert into facility (name, tagline, location, sort_order, beds, rdo, rdcs, nha, don, survey, rating_overall, rating_staffing, total_staff, open_roles) values ('Alpine', 'Rehabilitation & Nursing Center', null, 6, '99 beds', 'Stacie Atherton', 'Amanda Seibert', 'Jazmaine "Jaz" Smith', 'Angie Ivey', '🟡 Annual Survey Due', 3, 2, '31', '1');
insert into facility (name, tagline, location, sort_order, beds, rdo, rdcs, nha, don, survey, rating_overall, rating_staffing, total_staff, open_roles) values ('Atrium', 'Rehabilitation & Nursing Center', null, 7, null, null, null, null, null, null, null, null, null, null);
insert into facility (name, tagline, location, sort_order, beds, rdo, rdcs, nha, don, survey, rating_overall, rating_staffing, total_staff, open_roles) values ('Aspen Glen', 'Rehabilitation & Nursing Center', null, 8, '67 beds', 'Stacie Atherton', 'Amanda Seibert', 'Stephanie Wolfe', 'Ashley Scafide', '— New to Eminent · Confirm w/ Stacie Atherton', 5, 2, '0', '9');
commit;
